github_base_url: 'https://api.github.com/'
github_orga: 'cloudogu'
forgejo_base_url: 'https://forgejo.cloudogu.com/'
forgejo_orga: 'mirrors'
webhook_url: 'https://chat.googleapis.com/v1/spaces/FOO/messages?key=BAR&token=BAZ'
cron-spec: '30 05 * * *'
time-zone: 'Europe/Berlin'
