{
  "github_base_url": "https://api.github.com/",
  "github_orga": "cloudogu",
  "github_token": "SECRET",
  "forgejo_base_url": "https://codeberg.org/api/v1",
  "forgejo_orga": "cloudogu",
  "forgejo_token": "SECRET"
}
