/*
Forgejo API

This documentation describes the Forgejo API.

API version: 12.0.1+gitea-1.22.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forgejo

import (
	"encoding/json"
)

// checks if the WikiCommitList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WikiCommitList{}

// WikiCommitList WikiCommitList commit/revision list
type WikiCommitList struct {
	Commits []WikiCommit `json:"commits,omitempty"`
	Count   *int64       `json:"count,omitempty"`
}

// NewWikiCommitList instantiates a new WikiCommitList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWikiCommitList() *WikiCommitList {
	this := WikiCommitList{}
	return &this
}

// NewWikiCommitListWithDefaults instantiates a new WikiCommitList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWikiCommitListWithDefaults() *WikiCommitList {
	this := WikiCommitList{}
	return &this
}

// GetCommits returns the Commits field value if set, zero value otherwise.
func (o *WikiCommitList) GetCommits() []WikiCommit {
	if o == nil || IsNil(o.Commits) {
		var ret []WikiCommit
		return ret
	}
	return o.Commits
}

// GetCommitsOk returns a tuple with the Commits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WikiCommitList) GetCommitsOk() ([]WikiCommit, bool) {
	if o == nil || IsNil(o.Commits) {
		return nil, false
	}
	return o.Commits, true
}

// HasCommits returns a boolean if a field has been set.
func (o *WikiCommitList) HasCommits() bool {
	if o != nil && !IsNil(o.Commits) {
		return true
	}

	return false
}

// SetCommits gets a reference to the given []WikiCommit and assigns it to the Commits field.
func (o *WikiCommitList) SetCommits(v []WikiCommit) {
	o.Commits = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *WikiCommitList) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WikiCommitList) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *WikiCommitList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *WikiCommitList) SetCount(v int64) {
	o.Count = &v
}

func (o WikiCommitList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WikiCommitList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Commits) {
		toSerialize["commits"] = o.Commits
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableWikiCommitList struct {
	value *WikiCommitList
	isSet bool
}

func (v NullableWikiCommitList) Get() *WikiCommitList {
	return v.value
}

func (v *NullableWikiCommitList) Set(val *WikiCommitList) {
	v.value = val
	v.isSet = true
}

func (v NullableWikiCommitList) IsSet() bool {
	return v.isSet
}

func (v *NullableWikiCommitList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWikiCommitList(val *WikiCommitList) *NullableWikiCommitList {
	return &NullableWikiCommitList{value: val, isSet: true}
}

func (v NullableWikiCommitList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWikiCommitList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
