/*
Forgejo API

This documentation describes the Forgejo API.

API version: 12.0.1+gitea-1.22.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forgejo

import (
	"encoding/json"
)

// checks if the FileLinksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileLinksResponse{}

// FileLinksResponse FileLinksResponse contains the links for a repo's file
type FileLinksResponse struct {
	Git  *string `json:"git,omitempty"`
	Html *string `json:"html,omitempty"`
	Self *string `json:"self,omitempty"`
}

// NewFileLinksResponse instantiates a new FileLinksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileLinksResponse() *FileLinksResponse {
	this := FileLinksResponse{}
	return &this
}

// NewFileLinksResponseWithDefaults instantiates a new FileLinksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileLinksResponseWithDefaults() *FileLinksResponse {
	this := FileLinksResponse{}
	return &this
}

// GetGit returns the Git field value if set, zero value otherwise.
func (o *FileLinksResponse) GetGit() string {
	if o == nil || IsNil(o.Git) {
		var ret string
		return ret
	}
	return *o.Git
}

// GetGitOk returns a tuple with the Git field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileLinksResponse) GetGitOk() (*string, bool) {
	if o == nil || IsNil(o.Git) {
		return nil, false
	}
	return o.Git, true
}

// HasGit returns a boolean if a field has been set.
func (o *FileLinksResponse) HasGit() bool {
	if o != nil && !IsNil(o.Git) {
		return true
	}

	return false
}

// SetGit gets a reference to the given string and assigns it to the Git field.
func (o *FileLinksResponse) SetGit(v string) {
	o.Git = &v
}

// GetHtml returns the Html field value if set, zero value otherwise.
func (o *FileLinksResponse) GetHtml() string {
	if o == nil || IsNil(o.Html) {
		var ret string
		return ret
	}
	return *o.Html
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileLinksResponse) GetHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.Html) {
		return nil, false
	}
	return o.Html, true
}

// HasHtml returns a boolean if a field has been set.
func (o *FileLinksResponse) HasHtml() bool {
	if o != nil && !IsNil(o.Html) {
		return true
	}

	return false
}

// SetHtml gets a reference to the given string and assigns it to the Html field.
func (o *FileLinksResponse) SetHtml(v string) {
	o.Html = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *FileLinksResponse) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileLinksResponse) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *FileLinksResponse) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *FileLinksResponse) SetSelf(v string) {
	o.Self = &v
}

func (o FileLinksResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileLinksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Git) {
		toSerialize["git"] = o.Git
	}
	if !IsNil(o.Html) {
		toSerialize["html"] = o.Html
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableFileLinksResponse struct {
	value *FileLinksResponse
	isSet bool
}

func (v NullableFileLinksResponse) Get() *FileLinksResponse {
	return v.value
}

func (v *NullableFileLinksResponse) Set(val *FileLinksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFileLinksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFileLinksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileLinksResponse(val *FileLinksResponse) *NullableFileLinksResponse {
	return &NullableFileLinksResponse{value: val, isSet: true}
}

func (v NullableFileLinksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileLinksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
