/*
Forgejo API

This documentation describes the Forgejo API.

API version: 12.0.1+gitea-1.22.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forgejo

import (
	"encoding/json"
)

// checks if the GeneralRepoSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeneralRepoSettings{}

// GeneralRepoSettings GeneralRepoSettings contains global repository settings exposed by API
type GeneralRepoSettings struct {
	ForksDisabled *bool `json:"forks_disabled,omitempty"`
	HttpGitDisabled *bool `json:"http_git_disabled,omitempty"`
	LfsDisabled *bool `json:"lfs_disabled,omitempty"`
	MigrationsDisabled *bool `json:"migrations_disabled,omitempty"`
	MirrorsDisabled *bool `json:"mirrors_disabled,omitempty"`
	StarsDisabled *bool `json:"stars_disabled,omitempty"`
	TimeTrackingDisabled *bool `json:"time_tracking_disabled,omitempty"`
}

// NewGeneralRepoSettings instantiates a new GeneralRepoSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneralRepoSettings() *GeneralRepoSettings {
	this := GeneralRepoSettings{}
	return &this
}

// NewGeneralRepoSettingsWithDefaults instantiates a new GeneralRepoSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneralRepoSettingsWithDefaults() *GeneralRepoSettings {
	this := GeneralRepoSettings{}
	return &this
}

// GetForksDisabled returns the ForksDisabled field value if set, zero value otherwise.
func (o *GeneralRepoSettings) GetForksDisabled() bool {
	if o == nil || IsNil(o.ForksDisabled) {
		var ret bool
		return ret
	}
	return *o.ForksDisabled
}

// GetForksDisabledOk returns a tuple with the ForksDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralRepoSettings) GetForksDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ForksDisabled) {
		return nil, false
	}
	return o.ForksDisabled, true
}

// HasForksDisabled returns a boolean if a field has been set.
func (o *GeneralRepoSettings) HasForksDisabled() bool {
	if o != nil && !IsNil(o.ForksDisabled) {
		return true
	}

	return false
}

// SetForksDisabled gets a reference to the given bool and assigns it to the ForksDisabled field.
func (o *GeneralRepoSettings) SetForksDisabled(v bool) {
	o.ForksDisabled = &v
}

// GetHttpGitDisabled returns the HttpGitDisabled field value if set, zero value otherwise.
func (o *GeneralRepoSettings) GetHttpGitDisabled() bool {
	if o == nil || IsNil(o.HttpGitDisabled) {
		var ret bool
		return ret
	}
	return *o.HttpGitDisabled
}

// GetHttpGitDisabledOk returns a tuple with the HttpGitDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralRepoSettings) GetHttpGitDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.HttpGitDisabled) {
		return nil, false
	}
	return o.HttpGitDisabled, true
}

// HasHttpGitDisabled returns a boolean if a field has been set.
func (o *GeneralRepoSettings) HasHttpGitDisabled() bool {
	if o != nil && !IsNil(o.HttpGitDisabled) {
		return true
	}

	return false
}

// SetHttpGitDisabled gets a reference to the given bool and assigns it to the HttpGitDisabled field.
func (o *GeneralRepoSettings) SetHttpGitDisabled(v bool) {
	o.HttpGitDisabled = &v
}

// GetLfsDisabled returns the LfsDisabled field value if set, zero value otherwise.
func (o *GeneralRepoSettings) GetLfsDisabled() bool {
	if o == nil || IsNil(o.LfsDisabled) {
		var ret bool
		return ret
	}
	return *o.LfsDisabled
}

// GetLfsDisabledOk returns a tuple with the LfsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralRepoSettings) GetLfsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.LfsDisabled) {
		return nil, false
	}
	return o.LfsDisabled, true
}

// HasLfsDisabled returns a boolean if a field has been set.
func (o *GeneralRepoSettings) HasLfsDisabled() bool {
	if o != nil && !IsNil(o.LfsDisabled) {
		return true
	}

	return false
}

// SetLfsDisabled gets a reference to the given bool and assigns it to the LfsDisabled field.
func (o *GeneralRepoSettings) SetLfsDisabled(v bool) {
	o.LfsDisabled = &v
}

// GetMigrationsDisabled returns the MigrationsDisabled field value if set, zero value otherwise.
func (o *GeneralRepoSettings) GetMigrationsDisabled() bool {
	if o == nil || IsNil(o.MigrationsDisabled) {
		var ret bool
		return ret
	}
	return *o.MigrationsDisabled
}

// GetMigrationsDisabledOk returns a tuple with the MigrationsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralRepoSettings) GetMigrationsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.MigrationsDisabled) {
		return nil, false
	}
	return o.MigrationsDisabled, true
}

// HasMigrationsDisabled returns a boolean if a field has been set.
func (o *GeneralRepoSettings) HasMigrationsDisabled() bool {
	if o != nil && !IsNil(o.MigrationsDisabled) {
		return true
	}

	return false
}

// SetMigrationsDisabled gets a reference to the given bool and assigns it to the MigrationsDisabled field.
func (o *GeneralRepoSettings) SetMigrationsDisabled(v bool) {
	o.MigrationsDisabled = &v
}

// GetMirrorsDisabled returns the MirrorsDisabled field value if set, zero value otherwise.
func (o *GeneralRepoSettings) GetMirrorsDisabled() bool {
	if o == nil || IsNil(o.MirrorsDisabled) {
		var ret bool
		return ret
	}
	return *o.MirrorsDisabled
}

// GetMirrorsDisabledOk returns a tuple with the MirrorsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralRepoSettings) GetMirrorsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.MirrorsDisabled) {
		return nil, false
	}
	return o.MirrorsDisabled, true
}

// HasMirrorsDisabled returns a boolean if a field has been set.
func (o *GeneralRepoSettings) HasMirrorsDisabled() bool {
	if o != nil && !IsNil(o.MirrorsDisabled) {
		return true
	}

	return false
}

// SetMirrorsDisabled gets a reference to the given bool and assigns it to the MirrorsDisabled field.
func (o *GeneralRepoSettings) SetMirrorsDisabled(v bool) {
	o.MirrorsDisabled = &v
}

// GetStarsDisabled returns the StarsDisabled field value if set, zero value otherwise.
func (o *GeneralRepoSettings) GetStarsDisabled() bool {
	if o == nil || IsNil(o.StarsDisabled) {
		var ret bool
		return ret
	}
	return *o.StarsDisabled
}

// GetStarsDisabledOk returns a tuple with the StarsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralRepoSettings) GetStarsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.StarsDisabled) {
		return nil, false
	}
	return o.StarsDisabled, true
}

// HasStarsDisabled returns a boolean if a field has been set.
func (o *GeneralRepoSettings) HasStarsDisabled() bool {
	if o != nil && !IsNil(o.StarsDisabled) {
		return true
	}

	return false
}

// SetStarsDisabled gets a reference to the given bool and assigns it to the StarsDisabled field.
func (o *GeneralRepoSettings) SetStarsDisabled(v bool) {
	o.StarsDisabled = &v
}

// GetTimeTrackingDisabled returns the TimeTrackingDisabled field value if set, zero value otherwise.
func (o *GeneralRepoSettings) GetTimeTrackingDisabled() bool {
	if o == nil || IsNil(o.TimeTrackingDisabled) {
		var ret bool
		return ret
	}
	return *o.TimeTrackingDisabled
}

// GetTimeTrackingDisabledOk returns a tuple with the TimeTrackingDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralRepoSettings) GetTimeTrackingDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.TimeTrackingDisabled) {
		return nil, false
	}
	return o.TimeTrackingDisabled, true
}

// HasTimeTrackingDisabled returns a boolean if a field has been set.
func (o *GeneralRepoSettings) HasTimeTrackingDisabled() bool {
	if o != nil && !IsNil(o.TimeTrackingDisabled) {
		return true
	}

	return false
}

// SetTimeTrackingDisabled gets a reference to the given bool and assigns it to the TimeTrackingDisabled field.
func (o *GeneralRepoSettings) SetTimeTrackingDisabled(v bool) {
	o.TimeTrackingDisabled = &v
}

func (o GeneralRepoSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeneralRepoSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ForksDisabled) {
		toSerialize["forks_disabled"] = o.ForksDisabled
	}
	if !IsNil(o.HttpGitDisabled) {
		toSerialize["http_git_disabled"] = o.HttpGitDisabled
	}
	if !IsNil(o.LfsDisabled) {
		toSerialize["lfs_disabled"] = o.LfsDisabled
	}
	if !IsNil(o.MigrationsDisabled) {
		toSerialize["migrations_disabled"] = o.MigrationsDisabled
	}
	if !IsNil(o.MirrorsDisabled) {
		toSerialize["mirrors_disabled"] = o.MirrorsDisabled
	}
	if !IsNil(o.StarsDisabled) {
		toSerialize["stars_disabled"] = o.StarsDisabled
	}
	if !IsNil(o.TimeTrackingDisabled) {
		toSerialize["time_tracking_disabled"] = o.TimeTrackingDisabled
	}
	return toSerialize, nil
}

type NullableGeneralRepoSettings struct {
	value *GeneralRepoSettings
	isSet bool
}

func (v NullableGeneralRepoSettings) Get() *GeneralRepoSettings {
	return v.value
}

func (v *NullableGeneralRepoSettings) Set(val *GeneralRepoSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneralRepoSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneralRepoSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneralRepoSettings(val *GeneralRepoSettings) *NullableGeneralRepoSettings {
	return &NullableGeneralRepoSettings{value: val, isSet: true}
}

func (v NullableGeneralRepoSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneralRepoSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


