/*
Forgejo API

This documentation describes the Forgejo API.

API version: 12.0.1+gitea-1.22.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forgejo

import (
	"encoding/json"
)

// checks if the ExternalWiki type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalWiki{}

// ExternalWiki ExternalWiki represents setting for external wiki
type ExternalWiki struct {
	// URL of external wiki.
	ExternalWikiUrl *string `json:"external_wiki_url,omitempty"`
}

// NewExternalWiki instantiates a new ExternalWiki object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalWiki() *ExternalWiki {
	this := ExternalWiki{}
	return &this
}

// NewExternalWikiWithDefaults instantiates a new ExternalWiki object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalWikiWithDefaults() *ExternalWiki {
	this := ExternalWiki{}
	return &this
}

// GetExternalWikiUrl returns the ExternalWikiUrl field value if set, zero value otherwise.
func (o *ExternalWiki) GetExternalWikiUrl() string {
	if o == nil || IsNil(o.ExternalWikiUrl) {
		var ret string
		return ret
	}
	return *o.ExternalWikiUrl
}

// GetExternalWikiUrlOk returns a tuple with the ExternalWikiUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalWiki) GetExternalWikiUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalWikiUrl) {
		return nil, false
	}
	return o.ExternalWikiUrl, true
}

// HasExternalWikiUrl returns a boolean if a field has been set.
func (o *ExternalWiki) HasExternalWikiUrl() bool {
	if o != nil && !IsNil(o.ExternalWikiUrl) {
		return true
	}

	return false
}

// SetExternalWikiUrl gets a reference to the given string and assigns it to the ExternalWikiUrl field.
func (o *ExternalWiki) SetExternalWikiUrl(v string) {
	o.ExternalWikiUrl = &v
}

func (o ExternalWiki) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalWiki) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalWikiUrl) {
		toSerialize["external_wiki_url"] = o.ExternalWikiUrl
	}
	return toSerialize, nil
}

type NullableExternalWiki struct {
	value *ExternalWiki
	isSet bool
}

func (v NullableExternalWiki) Get() *ExternalWiki {
	return v.value
}

func (v *NullableExternalWiki) Set(val *ExternalWiki) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalWiki) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalWiki) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalWiki(val *ExternalWiki) *NullableExternalWiki {
	return &NullableExternalWiki{value: val, isSet: true}
}

func (v NullableExternalWiki) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalWiki) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
