/*
Forgejo API

This documentation describes the Forgejo API.

API version: 12.0.1+gitea-1.22.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forgejo

import (
	"encoding/json"
	"time"
)

// checks if the GPGKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GPGKey{}

// GPGKey GPGKey a user GPG key to sign commit and tag in repository
type GPGKey struct {
	CanCertify        *bool         `json:"can_certify,omitempty"`
	CanEncryptComms   *bool         `json:"can_encrypt_comms,omitempty"`
	CanEncryptStorage *bool         `json:"can_encrypt_storage,omitempty"`
	CanSign           *bool         `json:"can_sign,omitempty"`
	CreatedAt         *time.Time    `json:"created_at,omitempty"`
	Emails            []GPGKeyEmail `json:"emails,omitempty"`
	ExpiresAt         *time.Time    `json:"expires_at,omitempty"`
	Id                *int64        `json:"id,omitempty"`
	KeyId             *string       `json:"key_id,omitempty"`
	PrimaryKeyId      *string       `json:"primary_key_id,omitempty"`
	PublicKey         *string       `json:"public_key,omitempty"`
	Subkeys           []GPGKey      `json:"subkeys,omitempty"`
	Verified          *bool         `json:"verified,omitempty"`
}

// NewGPGKey instantiates a new GPGKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGPGKey() *GPGKey {
	this := GPGKey{}
	return &this
}

// NewGPGKeyWithDefaults instantiates a new GPGKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGPGKeyWithDefaults() *GPGKey {
	this := GPGKey{}
	return &this
}

// GetCanCertify returns the CanCertify field value if set, zero value otherwise.
func (o *GPGKey) GetCanCertify() bool {
	if o == nil || IsNil(o.CanCertify) {
		var ret bool
		return ret
	}
	return *o.CanCertify
}

// GetCanCertifyOk returns a tuple with the CanCertify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetCanCertifyOk() (*bool, bool) {
	if o == nil || IsNil(o.CanCertify) {
		return nil, false
	}
	return o.CanCertify, true
}

// HasCanCertify returns a boolean if a field has been set.
func (o *GPGKey) HasCanCertify() bool {
	if o != nil && !IsNil(o.CanCertify) {
		return true
	}

	return false
}

// SetCanCertify gets a reference to the given bool and assigns it to the CanCertify field.
func (o *GPGKey) SetCanCertify(v bool) {
	o.CanCertify = &v
}

// GetCanEncryptComms returns the CanEncryptComms field value if set, zero value otherwise.
func (o *GPGKey) GetCanEncryptComms() bool {
	if o == nil || IsNil(o.CanEncryptComms) {
		var ret bool
		return ret
	}
	return *o.CanEncryptComms
}

// GetCanEncryptCommsOk returns a tuple with the CanEncryptComms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetCanEncryptCommsOk() (*bool, bool) {
	if o == nil || IsNil(o.CanEncryptComms) {
		return nil, false
	}
	return o.CanEncryptComms, true
}

// HasCanEncryptComms returns a boolean if a field has been set.
func (o *GPGKey) HasCanEncryptComms() bool {
	if o != nil && !IsNil(o.CanEncryptComms) {
		return true
	}

	return false
}

// SetCanEncryptComms gets a reference to the given bool and assigns it to the CanEncryptComms field.
func (o *GPGKey) SetCanEncryptComms(v bool) {
	o.CanEncryptComms = &v
}

// GetCanEncryptStorage returns the CanEncryptStorage field value if set, zero value otherwise.
func (o *GPGKey) GetCanEncryptStorage() bool {
	if o == nil || IsNil(o.CanEncryptStorage) {
		var ret bool
		return ret
	}
	return *o.CanEncryptStorage
}

// GetCanEncryptStorageOk returns a tuple with the CanEncryptStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetCanEncryptStorageOk() (*bool, bool) {
	if o == nil || IsNil(o.CanEncryptStorage) {
		return nil, false
	}
	return o.CanEncryptStorage, true
}

// HasCanEncryptStorage returns a boolean if a field has been set.
func (o *GPGKey) HasCanEncryptStorage() bool {
	if o != nil && !IsNil(o.CanEncryptStorage) {
		return true
	}

	return false
}

// SetCanEncryptStorage gets a reference to the given bool and assigns it to the CanEncryptStorage field.
func (o *GPGKey) SetCanEncryptStorage(v bool) {
	o.CanEncryptStorage = &v
}

// GetCanSign returns the CanSign field value if set, zero value otherwise.
func (o *GPGKey) GetCanSign() bool {
	if o == nil || IsNil(o.CanSign) {
		var ret bool
		return ret
	}
	return *o.CanSign
}

// GetCanSignOk returns a tuple with the CanSign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetCanSignOk() (*bool, bool) {
	if o == nil || IsNil(o.CanSign) {
		return nil, false
	}
	return o.CanSign, true
}

// HasCanSign returns a boolean if a field has been set.
func (o *GPGKey) HasCanSign() bool {
	if o != nil && !IsNil(o.CanSign) {
		return true
	}

	return false
}

// SetCanSign gets a reference to the given bool and assigns it to the CanSign field.
func (o *GPGKey) SetCanSign(v bool) {
	o.CanSign = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GPGKey) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GPGKey) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GPGKey) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetEmails returns the Emails field value if set, zero value otherwise.
func (o *GPGKey) GetEmails() []GPGKeyEmail {
	if o == nil || IsNil(o.Emails) {
		var ret []GPGKeyEmail
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetEmailsOk() ([]GPGKeyEmail, bool) {
	if o == nil || IsNil(o.Emails) {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *GPGKey) HasEmails() bool {
	if o != nil && !IsNil(o.Emails) {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []GPGKeyEmail and assigns it to the Emails field.
func (o *GPGKey) SetEmails(v []GPGKeyEmail) {
	o.Emails = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *GPGKey) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *GPGKey) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *GPGKey) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GPGKey) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GPGKey) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *GPGKey) SetId(v int64) {
	o.Id = &v
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *GPGKey) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *GPGKey) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *GPGKey) SetKeyId(v string) {
	o.KeyId = &v
}

// GetPrimaryKeyId returns the PrimaryKeyId field value if set, zero value otherwise.
func (o *GPGKey) GetPrimaryKeyId() string {
	if o == nil || IsNil(o.PrimaryKeyId) {
		var ret string
		return ret
	}
	return *o.PrimaryKeyId
}

// GetPrimaryKeyIdOk returns a tuple with the PrimaryKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetPrimaryKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryKeyId) {
		return nil, false
	}
	return o.PrimaryKeyId, true
}

// HasPrimaryKeyId returns a boolean if a field has been set.
func (o *GPGKey) HasPrimaryKeyId() bool {
	if o != nil && !IsNil(o.PrimaryKeyId) {
		return true
	}

	return false
}

// SetPrimaryKeyId gets a reference to the given string and assigns it to the PrimaryKeyId field.
func (o *GPGKey) SetPrimaryKeyId(v string) {
	o.PrimaryKeyId = &v
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise.
func (o *GPGKey) GetPublicKey() string {
	if o == nil || IsNil(o.PublicKey) {
		var ret string
		return ret
	}
	return *o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PublicKey) {
		return nil, false
	}
	return o.PublicKey, true
}

// HasPublicKey returns a boolean if a field has been set.
func (o *GPGKey) HasPublicKey() bool {
	if o != nil && !IsNil(o.PublicKey) {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given string and assigns it to the PublicKey field.
func (o *GPGKey) SetPublicKey(v string) {
	o.PublicKey = &v
}

// GetSubkeys returns the Subkeys field value if set, zero value otherwise.
func (o *GPGKey) GetSubkeys() []GPGKey {
	if o == nil || IsNil(o.Subkeys) {
		var ret []GPGKey
		return ret
	}
	return o.Subkeys
}

// GetSubkeysOk returns a tuple with the Subkeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetSubkeysOk() ([]GPGKey, bool) {
	if o == nil || IsNil(o.Subkeys) {
		return nil, false
	}
	return o.Subkeys, true
}

// HasSubkeys returns a boolean if a field has been set.
func (o *GPGKey) HasSubkeys() bool {
	if o != nil && !IsNil(o.Subkeys) {
		return true
	}

	return false
}

// SetSubkeys gets a reference to the given []GPGKey and assigns it to the Subkeys field.
func (o *GPGKey) SetSubkeys(v []GPGKey) {
	o.Subkeys = v
}

// GetVerified returns the Verified field value if set, zero value otherwise.
func (o *GPGKey) GetVerified() bool {
	if o == nil || IsNil(o.Verified) {
		var ret bool
		return ret
	}
	return *o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GPGKey) GetVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Verified) {
		return nil, false
	}
	return o.Verified, true
}

// HasVerified returns a boolean if a field has been set.
func (o *GPGKey) HasVerified() bool {
	if o != nil && !IsNil(o.Verified) {
		return true
	}

	return false
}

// SetVerified gets a reference to the given bool and assigns it to the Verified field.
func (o *GPGKey) SetVerified(v bool) {
	o.Verified = &v
}

func (o GPGKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GPGKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CanCertify) {
		toSerialize["can_certify"] = o.CanCertify
	}
	if !IsNil(o.CanEncryptComms) {
		toSerialize["can_encrypt_comms"] = o.CanEncryptComms
	}
	if !IsNil(o.CanEncryptStorage) {
		toSerialize["can_encrypt_storage"] = o.CanEncryptStorage
	}
	if !IsNil(o.CanSign) {
		toSerialize["can_sign"] = o.CanSign
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Emails) {
		toSerialize["emails"] = o.Emails
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.KeyId) {
		toSerialize["key_id"] = o.KeyId
	}
	if !IsNil(o.PrimaryKeyId) {
		toSerialize["primary_key_id"] = o.PrimaryKeyId
	}
	if !IsNil(o.PublicKey) {
		toSerialize["public_key"] = o.PublicKey
	}
	if !IsNil(o.Subkeys) {
		toSerialize["subkeys"] = o.Subkeys
	}
	if !IsNil(o.Verified) {
		toSerialize["verified"] = o.Verified
	}
	return toSerialize, nil
}

type NullableGPGKey struct {
	value *GPGKey
	isSet bool
}

func (v NullableGPGKey) Get() *GPGKey {
	return v.value
}

func (v *NullableGPGKey) Set(val *GPGKey) {
	v.value = val
	v.isSet = true
}

func (v NullableGPGKey) IsSet() bool {
	return v.isSet
}

func (v *NullableGPGKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGPGKey(val *GPGKey) *NullableGPGKey {
	return &NullableGPGKey{value: val, isSet: true}
}

func (v NullableGPGKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGPGKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
